#!/usr/bin/env bash
# Host tuning for a large containerlab BGP lab. Run as root before deploying.
#
# Every value below is either from a vendor's documented containerlab guidance or
# from FRR's own doc/user/Useful_Sysctl_Settings.md. Where a commonly-repeated
# tuning knob is actually a no-op, it is listed and explained rather than set.
set -euo pipefail
[ "$(id -u)" = 0 ] || { echo "run as root" >&2; exit 1; }

NODES="${1:-60}"
CONF=/etc/sysctl.d/99-vyos-ixp-stress.conf

echo "== tuning for ~${NODES} containerlab nodes"

# --- inotify -----------------------------------------------------------------
# containerlab documents no inotify guidance for the VyOS kind. The figures here
# follow the Arista cEOS page, which is the only kind with an explicit formula:
# fs.inotify.max_user_instances = nodes * 1250. VyOS nodes run full systemd plus
# FRR plus journald, so they are inotify-hungry in the same way. This is a
# borrowed heuristic, not vendor-sanctioned for VyOS.
INSTANCES=$(( NODES * 1250 ))
[ "$INSTANCES" -lt 8192 ] && INSTANCES=8192

# --- IPv6 FIB ----------------------------------------------------------------
# net.ipv6.route.max_size is a real, enforced ceiling on kernels < 6.3 and the
# classic cause of dropped IPv6 route installs at scale. It was deprecated in
# 6.3, so whether it binds depends on the running kernel. Set it either way; it
# is harmless where deprecated.
KREL=$(uname -r | cut -d. -f1,2)
echo "   kernel $KREL (net.ipv6.route.max_size is deprecated from 6.3 onwards)"

cat > "$CONF" <<SYSCTL
# Generated by vyos-ixp-stress/scripts/host-tune.sh for ~${NODES} nodes.

# inotify: borrowed from containerlab's cEOS formula (nodes * 1250).
fs.inotify.max_user_instances = ${INSTANCES}
fs.inotify.max_user_watches = 1048576

# ARP/NDP: a shared IXP peering LAN with hundreds of speakers blows through the
# default neighbour GC thresholds, and neighbour eviction looks exactly like
# next-hop unreachability in BGP.
net.ipv4.neigh.default.gc_thresh1 = 8192
net.ipv4.neigh.default.gc_thresh2 = 16384
net.ipv4.neigh.default.gc_thresh3 = 32768
net.ipv6.neigh.default.gc_thresh1 = 8192
net.ipv6.neigh.default.gc_thresh2 = 16384
net.ipv6.neigh.default.gc_thresh3 = 32768

# IPv6 FIB sizing (FRR's own recommended set uses 131072; raised for full tables).
net.ipv6.route.max_size = 524288
net.ipv6.route.gc_thresh = 262144
# Suppresses a netlink notification storm when an interface goes down, which is
# directly relevant to the zebra recvmsg-overrun failure mode.
net.ipv6.route.skip_notify_on_dev_down = 1

# Option memory. FRR documents sockopt_tcp_signature ENOMEM at several-hundred-peer
# scale with TCP-MD5; also consumed by large numbers of sockets generally.
net.core.optmem_max = 2097152

# Socket buffers. NOTE: zebra sets its own netlink receive buffer to 4 MiB using
# SO_RCVBUFFORCE, which BYPASSES net.core.rmem_max when it holds CAP_NET_ADMIN.
# Raising rmem_max often changes nothing for zebra. Verify the applied value with
# `vtysh -c 'show zebra'` and read the "Kernel socket buffer size" line.
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.core.netdev_max_backlog = 30000

# Many containers, many sockets, many veths.
net.ipv4.neigh.default.base_reachable_time_ms = 60000
fs.file-max = 4194304
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1

# Bridged peering LANs must not be filtered by the host's iptables.
net.bridge.bridge-nf-call-iptables = 0
net.bridge.bridge-nf-call-ip6tables = 0

# Do not swap a routing daemon out from under a latency measurement.
#
# The default (60) is tuned for general-purpose servers and is wrong for this
# workload, which is one ~8 GB anonymous-memory process plus 24 containers.
# Measured on T3 run 3, at 10:06-10:08 with **7.5 GiB available and 4.9 GiB
# free**, the kernel evicted ~6 GiB of anonymous pages — peaking at 60,000
# pages/s out while simultaneously faulting 14,000 pages/s back in. Swapping in
# and out at once, with a third of RAM free, is thrashing, not reclaim.
#
# 1 rather than 0: swap stays available as an emergency reserve, so a
# transient anonymous-memory spike degrades instead of inviting the OOM killer
# to take bgpd — or worse, a peer container, which would read as a DUT
# failure. It just stops the kernel doing it routinely.
#
# Leave swap ENABLED. See FINDINGS.md "Swap: why it is on, and set to 1".
vm.swappiness = 1
SYSCTL

modprobe br_netfilter 2>/dev/null || true
sysctl -q --load "$CONF" || sysctl --load "$CONF" || true

# --- file descriptors --------------------------------------------------------
mkdir -p /etc/systemd/system/docker.service.d
cat > /etc/systemd/system/docker.service.d/99-stress-limits.conf <<'UNIT'
[Service]
LimitNOFILE=1048576
LimitNPROC=infinity
LimitCORE=infinity
TasksMax=infinity
UNIT
systemctl daemon-reload
echo "   docker limits written; run 'systemctl restart docker' to apply"

echo
echo "== NOT set, deliberately"
echo "   net.ipv4.route.max_size — deprecated since kernel 3.6 (the IPv4 route"
echo "     cache is gone). It is writable but has no effect on FIB capacity, and"
echo "     it is absent from FRR's own recommended sysctl set. IPv4 FIB size is"
echo "     bounded by memory, so IPv4 failure shows up as memory pressure, not as"
echo "     a 'table full' error."
echo
echo "== applied: $CONF"
echo "   Remember: 'set system frr descriptors <n>' on the DUT is what raises"
echo "   FRR's own --limit-fds, and it needs a routing-daemon restart."
